name: DOTNET API CI/CD

permissions:
      id-token: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Build
      run: dotnet build -c Release
      working-directory: ./dolan-webapp
    - name: Publish
      run: dotnet publish -c Release
      working-directory: ./dolan-webapp
    - name: Zip WebApp Package
      run: zip -r ../deploy.zip ./
      working-directory: ./dolan-webapp/dolan-webapp/bin/Release/net7.0/publish/
    - name: Upload Deployment Zip
      uses: actions/upload-artifact@v4
      with:
        name: deployment_zip
        path: ./dolan-webapp/dolan-webapp/bin/Release/net7.0/deploy.zip
      
  deploy_to_dev:
    runs-on: ubuntu-latest
    needs: build
    environment: development
    steps:
    - name: Download a Deployment Zip
      uses: actions/download-artifact@v4
      with:
        name: deployment_zip

  deploy_to_preprod:
    runs-on: ubuntu-latest
    needs: build
    environment: preprod
    steps:
    - name: Download a Deployment Zip
      uses: actions/download-artifact@v4
      with:
        name: deployment_zip

  deploy_to_prod:
    runs-on: ubuntu-latest
    needs: build
    environment: prod
    steps:
    - name: Download a Deployment Zip
      uses: actions/download-artifact@v4
      with:
        name: deployment_zip


          
 
