name: SonarQube

on:
  push:
    branches:
      - main


jobs:
  build:
    name: Sonar Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      
      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet test
        run: dotnet test --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ${{ github.workspace }}/coverage
        
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}      
        with:
          projectBaseDir: ${{ github.workspace }}
          args: >
            -Dsonar.python.coverage.reportPaths=${{ github.workspace }}/coverage/*/coverage.cobertura.xml
            -Dsonar.verbose=true
            -Dsonar.projectKey=doolan-webapp
